---
- hosts: saathi
  vars:
    project_path: /home/saish/saathi-app/saathi-frontend
    root_path: /home/saish/saathi-app

  tasks:
    - name: Slurp host file
      slurp:
        src: "/home/saish/.token"
      register: slurpfile

    - name: Ensure project directory exists
      file:
        path: "{{ project_path }}"
        state: directory
        mode: '0755'

    - name: Fetch the latest code
      git:
        repo: https://github.com/Vinod-V3/saathi-frontend
        dest: "{{ project_path }}"
        version: "{{ gitBranch }}"
        force: yes

    - name: set permission
      shell: chmod 744 {{ project_path }}/src/scripts/json2env.sh

    - name: Fetch .env from Vault
      shell: >
        curl --location --request GET '{{ vaultAddress }}saathi-env'
        --header 'X-Vault-Token: {{ slurpfile['content'] | b64decode }}' | jq '.data' > '{{ project_path }}/data2.json'
      register: env_response

    - name: generate .env
      shell: cat {{ project_path }}/data2.json | {{ project_path }}/src/scripts/json2env.sh > {{ project_path }}/.env
      register: envConfig

    - debug:
        msg: " cred {{ envConfig }} "

    - name: Remove the old build
      shell: "rm -rf {{ project_path }}/build"

    - name: Remove node_modules folder
      shell: "rm -rf {{ project_path }}/node_modules"

    - name: Clear npm cache
      shell: "npm cache clean --force"

    - name: Install dependencies
      shell: "cd {{ project_path }} && npm i --force"

    - name: Fetch pm2 config file
      shell: >
        curl --location --request GET '{{ vaultAddress }}saathiPortalPM2Config'
        --header 'X-Vault-Token: {{ slurpfile['content'] | b64decode }}'
        | jq '.data.data' > '{{ project_path }}/pm2.config.json'

    - name: Build saathi app
      shell: "cd {{ project_path }} && npm run build"

    - name: Start pm2
      shell: "cd {{ project_path }} && pm2 start pm2.config.json"